name: Publish Documentation

on:
  workflow_dispatch: { }
  pull_request: { }

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unity Solution
        uses: ./.github/actions/unity
      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - run: dotnet tool update -g docfx
      - run: docfx .docfx/docfx.json
